version: '3.4'

services:
  webweather.api:
    image: ${DOCKER_REGISTRY-}webweatherapi
    build:
      context: .
      dockerfile: WebWeather.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"